name: "Discord Bot Addon"
version: "1.0.0"
slug: "discord_bot_addon"
description: "Ein einfaches Home Assistant Add-on für einen Discord Bot."
startup: services
boot: auto
options:
  token: ""
  channel_id: ""
schema:
  token: str
  channel_id: str
arch:
  - amd64
  - aarch64
